// Generated by scripts/build_map_previews.py - edit the generator, not this file.
// Facts come from the shipped data/maps/*.map through scripts/neon_mapread.py, so a map
// edit that changes a spawn, a checkpoint or the geometry updates the Maps page with it.
#ifndef GAME_CLIENT_NEON_MAPS_GEN_H
#define GAME_CLIENT_NEON_MAPS_GEN_H

#include <cstddef>

namespace NeonMaps
{
struct SMapFacts
{
	const char *m_pName;
	const char *m_pBlurb;
	int m_PreviewCell;
	int m_TilesW;
	int m_TilesH;
	int m_Spawns;
	int m_SolidTiles;
	int m_DeathTiles;
	int m_NohookTiles;
	int m_StartTiles;
	int m_FinishTiles;
	int m_Checkpoints;
	int m_Teleports;
	int m_Pickups;
	int m_Hazards;
	bool m_RaceReady;
	bool m_NeonDmReady;
	bool m_BaseGame;
	const char *m_pMode;
	const char *m_pTileset;
	const char *m_pLicense;
};

inline constexpr SMapFacts g_aFacts[] = {
	{"Neon Relay Basin", "сбалансированный заезд-введение: полки, три чекпоинта, река смерти", 0, 220, 70, 3, 3673, 100, 35, 1, 1, 3, 0, 0, 0, true, true, false, "race", "neonrelay_sound_tiles", "Zlib"},
	{"Chromatic Canyon", "хук-роут над каньоном: 163 смертельных тайла и ни одного no-hook", 1, 240, 90, 3, 5503, 163, 0, 1, 1, 3, 0, 0, 0, true, true, false, "race", "neonrelay_folds_tiles", "Zlib"},
	{"Vector Spire", "зигзаг полок вверх, 6 чекпоинтов и много no-hook под потолком", 2, 160, 110, 3, 1764, 24, 44, 1, 1, 6, 0, 0, 0, true, true, false, "race", "neonrelay_circuit_tiles", "Zlib"},
	{"Midnight Circuit", "быстрый слалом по плоскому кругу: 5 чекпоинтов, минимум смерти", 3, 260, 56, 3, 4135, 22, 81, 1, 1, 5, 0, 0, 0, true, true, false, "race", "neonrelay_chrome_tiles", "Zlib"},
	{"Aurora Ascent", "лесенка под полосой авроры, самая длинная разметка заезда после Warmup", 4, 200, 100, 3, 5246, 550, 200, 1, 1, 4, 0, 0, 0, true, true, false, "race", "neonrelay_folds_tiles", "Zlib"},
	{"Neon Relay Warmup", "разминка: 35 стартовых площадок, без дропов и без очков", 5, 176, 48, 1, 2983, 0, 2943, 35, 31, 0, 0, 0, 0, true, false, false, "race", "neonrelay_learn_terrain", "Zlib"},
	{"Gold Mine", "закрытая арена с укрытиями: 10 спавнов, 986 тайлов no-hook, есть ниндзя", 6, 211, 137, 10, 21539, 0, 986, 6, 17, 0, 0, 2, 0, true, true, true, "race", "", "CC-BY-SA"},
	{"LearnToPlay", "тренировочный полигон базы с 56 щитами и 12 ловушками", 7, 622, 200, 9, 8244, 0, 6732, 8, 10, 0, 0, 64, 12, true, true, true, "race", "", "CC-BY-SA"},
	{"LearnToPlay Sound", "тот же полигон с звуковым слоем: 55 слоёв, 20 289 квадов", 8, 622, 200, 9, 8244, 0, 6732, 8, 10, 0, 0, 64, 12, true, true, true, "race", "", "CC-BY-SA"},
	{"LearnToPlay Sound Heights", "вариант Sound с другим декором: те же 56 щитов и 12 ловушек", 9, 622, 200, 9, 8256, 0, 6732, 8, 10, 0, 0, 64, 12, true, true, true, "race", "", "CC-BY-SA"},
	{"Sunny Side Up", "широкая 1200x200 карта с 594 квадами декора — площадка для больших составов", 10, 1200, 200, 3, 208554, 0, 1844, 11, 11, 0, 0, 0, 0, true, true, true, "race", "", "CC-BY-SA"},
	{"Tsunami", "самая плотная арена поставки: 105 101 тайл породы и 14 спавнов", 11, 561, 201, 14, 105101, 0, 560, 5, 11, 6, 0, 8, 0, true, true, true, "race", "", "CC-BY-SA"},
	{"Tutorial", "обучающий маршрут на 2210 тайлов: 24 финишных площадки, лицензия CC-BY-SA", 12, 2210, 110, 1, 112831, 0, 9247, 4, 24, 0, 0, 4, 0, true, false, true, "race", "", "CC-BY-SA"},
	{"coverage", "служебная карта тестов репозитория: по одной штуке всех типов сущностей", 13, 50, 50, 1, 1387, 38, 492, 2, 7, 2, 0, 5, 15, true, false, true, "race", "", ""},
	{"ctf1", "флаговая карта базы: два флага, много щитов и здоровья", 14, 70, 50, 8, 1975, 0, 0, 0, 0, 0, 0, 28, 0, false, true, true, "ctf", "", ""},
	{"ctf2", "флаговая карта базы: два флага, много щитов и здоровья", 15, 220, 85, 14, 10585, 0, 0, 0, 0, 0, 0, 75, 2, false, true, true, "ctf", "", ""},
	{"ctf3", "флаговая карта базы: два флага, много щитов и здоровья", 16, 145, 43, 8, 3551, 0, 0, 0, 0, 0, 0, 43, 1, false, true, true, "ctf", "", ""},
	{"ctf4", "флаговая карта базы: два флага, много щитов и здоровья", 17, 181, 51, 8, 5082, 0, 0, 0, 0, 0, 0, 53, 1, false, true, true, "ctf", "", ""},
	{"ctf5", "флаговая карта базы: два флага, много щитов и здоровья", 18, 270, 120, 16, 6555, 270, 921, 0, 0, 0, 0, 94, 3, false, true, true, "ctf", "", ""},
	{"ctf6", "флаговая карта базы: два флага, много щитов и здоровья", 19, 295, 65, 10, 9512, 169, 0, 0, 0, 0, 0, 83, 3, false, true, true, "ctf", "", ""},
	{"ctf7", "флаговая карта базы: два флага, много щитов и здоровья", 20, 70, 50, 6, 1919, 0, 0, 0, 0, 0, 0, 36, 0, false, true, true, "ctf", "", ""},
	{"dm1", "закрытая deathmatch-арена базы: спавны по кругу и полный набор дропов", 21, 60, 50, 8, 1535, 0, 0, 0, 0, 0, 0, 24, 0, false, true, true, "deathmatch", "", ""},
	{"dm2", "закрытая deathmatch-арена базы: спавны по кругу и полный набор дропов", 22, 130, 90, 7, 6071, 0, 0, 0, 0, 0, 0, 42, 1, false, true, true, "deathmatch", "", ""},
	{"dm6", "закрытая deathmatch-арена базы: спавны по кругу и полный набор дропов", 23, 90, 78, 9, 4081, 17, 57, 0, 0, 0, 0, 34, 1, false, true, true, "deathmatch", "", ""},
	{"dm7", "закрытая deathmatch-арена базы: спавны по кругу и полный набор дропов", 24, 146, 120, 9, 11088, 0, 0, 0, 0, 0, 0, 55, 2, false, true, true, "deathmatch", "", ""},
	{"dm8", "закрытая deathmatch-арена базы: спавны по кругу и полный набор дропов", 25, 62, 50, 4, 1067, 15, 29, 0, 0, 0, 0, 27, 0, false, true, true, "deathmatch", "", ""},
	{"dm9", "закрытая deathmatch-арена базы: спавны по кругу и полный набор дропов", 26, 50, 45, 4, 1115, 0, 0, 0, 0, 0, 0, 16, 0, false, true, true, "deathmatch", "", ""},
};
inline constexpr size_t NUM_CARDS = std::size(g_aFacts);

// Preview sheet geometry: COLS cells per row in data/ui/maps/previews.png, 2:1 cells.
inline constexpr int PREVIEW_CELL_W = 320;
inline constexpr int PREVIEW_CELL_H = 160;
inline constexpr int PREVIEW_COLS = 5;
inline constexpr int PREVIEW_CELLS = 27;
inline constexpr int PREVIEW_ROWS = (PREVIEW_CELLS + PREVIEW_COLS - 1) / PREVIEW_COLS;
} // namespace NeonMaps

#endif // GAME_CLIENT_NEON_MAPS_GEN_H
