// Generated by scripts/build_map_previews.py - edit the generator, not this file.
// Facts come from the shipped data/maps/*.map through scripts/neon_mapread.py, so a map
// edit that changes a spawn, a checkpoint or the geometry updates the Maps page with it.
#ifndef GAME_CLIENT_NEON_MAPS_GEN_H
#define GAME_CLIENT_NEON_MAPS_GEN_H

#include <cstddef>

namespace NeonMaps
{
struct SMapFacts
{
	const char *m_pName;
	const char *m_pBlurb;
	int m_PreviewCell;
	int m_TilesW;
	int m_TilesH;
	int m_Spawns;
	int m_SolidTiles;
	int m_DeathTiles;
	int m_NohookTiles;
	int m_StartTiles;
	int m_FinishTiles;
	int m_Checkpoints;
	int m_Teleports;
	int m_Pickups;
	int m_Hazards;
	bool m_RaceReady;
	bool m_NeonDmReady;
	bool m_BaseGame;
	const char *m_pMode;
	const char *m_pTileset;
	const char *m_pLicense;
};

inline constexpr SMapFacts g_aFacts[] = {
	{"Neon Relay Basin", "сбалансированный заезд-введение: полки, три чекпоинта, река смерти", 0, 220, 70, 3, 3673, 100, 35, 1, 1, 3, 0, 0, 0, true, true, false, "race", "neonrelay_sound_tiles", "Zlib"},
	{"Chromatic Canyon", "хук-роут над каньоном: 163 смертельных тайла и ни одного no-hook", 1, 240, 90, 3, 5503, 163, 0, 1, 1, 3, 0, 0, 0, true, true, false, "race", "neonrelay_folds_tiles", "Zlib"},
	{"Vector Spire", "зигзаг полок вверх, 6 чекпоинтов и много no-hook под потолком", 2, 160, 110, 3, 1764, 24, 44, 1, 1, 6, 0, 0, 0, true, true, false, "race", "neonrelay_circuit_tiles", "Zlib"},
	{"Midnight Circuit", "быстрый слалом по плоскому кругу: 5 чекпоинтов, минимум смерти", 3, 260, 56, 3, 4135, 22, 81, 1, 1, 5, 0, 0, 0, true, true, false, "race", "neonrelay_chrome_tiles", "Zlib"},
	{"Aurora Ascent", "лесенка под полосой авроры, самая длинная разметка заезда после Warmup", 4, 200, 100, 3, 5246, 550, 200, 1, 1, 4, 0, 0, 0, true, true, false, "race", "neonrelay_folds_tiles", "Zlib"},
	{"Neon Relay Warmup", "разминка: 35 стартовых площадок, без дропов и без очков", 5, 176, 48, 1, 2983, 0, 2943, 35, 31, 0, 0, 0, 0, true, false, false, "race", "neonrelay_learn_terrain", "Zlib"},
	{"Gold Mine", "закрытая арена с укрытиями: 10 спавнов, 986 тайлов no-hook, есть ниндзя", 6, 211, 137, 10, 21539, 0, 986, 6, 17, 0, 0, 2, 0, true, true, true, "race", "", "CC-BY-SA"},
	{"LearnToPlay", "тренировочный полигон базы с 56 щитами и 12 ловушками", 7, 622, 200, 9, 8244, 0, 6732, 8, 10, 0, 0, 64, 12, true, true, true, "race", "", "CC-BY-SA"},
	{"LearnToPlay Sound", "тот же полигон с звуковым слоем: 55 слоёв, 20 289 квадов", 8, 622, 200, 9, 8244, 0, 6732, 8, 10, 0, 0, 64, 12, true, true, true, "race", "", "CC-BY-SA"},
	{"LearnToPlay Sound Heights", "вариант Sound с другим декором: те же 56 щитов и 12 ловушек", 9, 622, 200, 9, 8256, 0, 6732, 8, 10, 0, 0, 64, 12, true, true, true, "race", "", "CC-BY-SA"},
	{"coverage", "служебная карта тестов репозитория: по одной штуке всех типов сущностей", 10, 50, 50, 1, 1387, 38, 492, 2, 7, 2, 0, 5, 15, true, false, true, "race", "", "CC-BY-SA"},
};
inline constexpr size_t NUM_CARDS = std::size(g_aFacts);

// Preview sheet geometry: COLS cells per row in data/ui/maps/previews.png, 2:1 cells.
inline constexpr int PREVIEW_CELL_W = 320;
inline constexpr int PREVIEW_CELL_H = 160;
inline constexpr int PREVIEW_COLS = 5;
inline constexpr int PREVIEW_CELLS = 11;
inline constexpr int PREVIEW_ROWS = (PREVIEW_CELLS + PREVIEW_COLS - 1) / PREVIEW_COLS;
} // namespace NeonMaps

#endif // GAME_CLIENT_NEON_MAPS_GEN_H
