// Generated by scripts/gen_potato_catalog.py. Do not edit.
#ifndef GAME_CLIENT_POTATO_CATALOG_H
#define GAME_CLIENT_POTATO_CATALOG_H
#include <base/str.h>
inline bool IsPotatoCatalogSkin(const char *pName)
{
	static const char *const s_apNames[] = {
		"potato_cool_guy_1",
		"potato_cool_girl_1",
		"potato_guy_2",
		"potato_girl_2",
		"potato_guy_3",
		"potato_guy_4",
		"potato_girl_3",
		"potato_girl_4",
		"potato_legend_guy",
		"potato_legend_girl",
	};
	for(const char *pAllowed : s_apNames)
		if(str_comp(pName, pAllowed) == 0)
			return true;
	return false;
}
#endif
