// Generated by scripts/gen_potato_catalog.py. Do not edit.
#ifndef GAME_CLIENT_POTATO_CATALOG_H
#define GAME_CLIENT_POTATO_CATALOG_H
#include <base/str.h>
struct CPotatoCatalogEntry
{
	const char *m_pSkin;
	const char *m_pName;
	const char *m_pRarity;
	int m_PriceSkr;
	const char *m_pNameRu;
	const char *m_pTitle;
	const char *m_pTitleRu;
	const char *m_pSkill;
	const char *m_pSkillRu;
	const char *m_pLegend;
	const char *m_pLegendRu;
};
inline constexpr CPotatoCatalogEntry POTATO_CATALOG[] = {
	{"potato_cool_guy_1", "Nox", "Common", 500, "Нокс", "Night runner", "Ночной трассер", "Reads a route and plans the next hook.", "Читает ритм трассы и выбирает точку для крюка.", "Nox delivered parcels across the neon rooftops. His worn jacket remembers hundreds of routes; his cyan lenses always face the next turn.", "Нокс доставлял посылки между крышами неонового города. Его потёртая куртка хранит следы сотен маршрутов, а бирюзовые линзы отражают следующий поворот."},
	{"potato_cool_girl_1", "Luma", "Common", 500, "Люма", "Team spark", "Искра команды", "Keeps the crew together through difficult sections.", "Поддерживает команду и находит выход из сложной секции.", "Luma made an abandoned station a home for racers. Pink hair and a turquoise bomber announce her arrival: nobody gets left behind.", "Люма превратила заброшенную станцию в место встреч гонщиков. Розовые волосы и бирюзовый бомбер видны издалека: если она на старте, никто не остаётся позади."},
	{"potato_guy_2", "Bit", "Common", 500, "Бит", "Circuit maker", "Мастер схем", "Remembers sequences and understands mechanisms.", "Запоминает последовательности и разбирается в механизмах.", "Bit built arcade machines from discarded parts. The circuits on his hoodie recall his favourite inventions, and his cap points toward the next adventure.", "Бит собирал игровые автоматы из списанных деталей. Теперь узоры на его худи повторяют схемы любимых устройств, а кепка неизменно повёрнута к следующему приключению."},
	{"potato_girl_2", "Roxy", "Common", 500, "Рокси", "Street rhythm", "Ритм улиц", "Finds her rhythm again after a missed jump.", "Держит темп и не теряется после неудачного прыжка.", "Roxy began on courtyard stages. She traded the stage for a race route, keeping her violet fringe and her habit of making every attempt a show.", "Рокси начинала с выступлений во дворах. Она сменила сцену на трассу, но сохранила фиолетовую чёлку, дерзкую улыбку и привычку превращать каждую попытку в шоу."},
	{"potato_guy_3", "Riff", "Common", 500, "Риф", "Dawn courier", "Курьер рассвета", "Looks for a clear route through unfamiliar maps.", "Ищет понятную линию движения на незнакомой карте.", "Riff knows the city from his morning deliveries. District patches cover his denim jacket; he starts early to greet the sunrise at the finish.", "Риф знает город по утренним доставкам. На джинсовой куртке остались нашивки старых районов; он приходит на старт раньше всех, чтобы встретить рассвет на финише."},
	{"potato_guy_4", "Bruno", "Rare", 1000, "Бруно", "Steady resolve", "Стальная выдержка", "Practises difficult sections and helps newcomers.", "Терпеливо отрабатывает сложные участки и помогает новичкам.", "Bruno repaired motorcycles on the night shift. His bandana and metal studs remain, but behind the tough look is the most patient mentor in the district.", "Бруно чинил мотоциклы ночной смены. Бандана и металлические заклёпки остались с тех времён. За суровым видом скрывается самый терпеливый наставник квартала."},
	{"potato_girl_3", "Vega", "Rare", 1000, "Вега", "Pulse captain", "Капитан импульса", "Coordinates the crew and sets a shared rhythm.", "Согласует действия команды и задаёт общий темп.", "Vega formed her district’s first crew from strangers. Her turquoise hair and varsity jacket became a promise: a finish matters when everyone reaches it.", "Вега собрала первую команду своего района из незнакомцев. Бирюзовая прядь и клубная куртка стали её знаком: победа имеет смысл, когда до финиша дошли все."},
	{"potato_girl_4", "Stella", "Rare", 1000, "Стелла", "Cool precision", "Холодная точность", "Studies mistakes and practises a route until it feels natural.", "Разбирает ошибки и доводит маршрут до уверенного прохождения.", "Stella photographed the city at night before entering the frame herself. Blonde hair, dark leather and a calm gaze are her signature on every route.", "Стелла фотографировала ночной город, пока сама не оказалась в кадре гонки. Светлые пряди, тёмная кожа куртки и спокойный взгляд — её подпись на каждой трассе."},
	{"potato_legend_guy", "Midas", "Legendary", 2000, "Мидас", "Keeper of the finish", "Хранитель финала", "Keeps his composure on a decisive attempt.", "Сохраняет хладнокровие в решающей попытке.", "Midas never bought his crown: friends made it from local tournament medals. His gold chains recall not wealth, but the people who shared the journey.", "Мидас не покупал свою корону: друзья собрали её из медалей дворовых турниров. Золотые цепи напоминают не о богатстве, а о людях, с которыми он прошёл путь."},
	{"potato_legend_girl", "Aurora", "Legendary", 2000, "Аврора", "Neon queen", "Королева неона", "Inspires her crew to try again after defeat.", "Вдохновляет команду пробовать снова после поражения.", "Aurora lit the first night race after a long silence. Pink hair, a radiant crown and luminous costume patterns became symbols of a city coming back to life.", "Аврора зажгла огни первой ночной гонки после долгого затишья. Розовые волосы, сияющая корона и узоры на костюме стали символом возвращения города к жизни."},
};
inline bool IsPotatoCatalogSkin(const char *pName)
{
	for(const auto &Entry : POTATO_CATALOG)
		if(str_comp(pName, Entry.m_pSkin) == 0)
			return true;
	return false;
}
#endif
