// Generated by scripts/gen_race_catalog.ts. Do not edit.
#ifndef GAME_CLIENT_RACE_CATALOG_H
#define GAME_CLIENT_RACE_CATALOG_H
struct CRaceCatalogEntry
{
	const char *m_pName;
	const char *m_pPlayers;
	const char *m_pEntry;
	bool m_LegendaryOnly;
};
inline constexpr CRaceCatalogEntry RACE_CATALOG[] = {
	{"Micro Sprint", "10", "50", false},
	{"Neon Dash", "20", "100", false},
	{"Chromatic Cup", "50", "500", false},
	{"Grand Prix", "100+", "2000", false},
	{"Legend Freeroll", "—", "0", true},
};
#endif
