#!/usr/bin/env python3
"""Landing-page integrity gate (catalog item 104; also 105, 119).

The 2026 pattern (Polymarket, 25 June: a compromised vendor injected a script
that harvested approvals) is a *delivery* attack: the contract is fine, the
domain is fine, the page the player loads is not. The landing pages are static
and must stay that way:

* no external script/style/frame/form origins — every asset is same-origin;
* no `eval`, `new Function`, `document.write`, `innerHTML =`, or `iframe`;
* `_headers` keeps the strict CSP (`default-src 'self'`, `connect-src 'none'`,
  `frame-ancestors 'none'`, `object-src 'none'`);
* every served file is hashed into `design/landing/INTEGRITY.json`, so any
  change to the shipped bundle is visible in review (and can be compared with
  the hash in the deployment log — the "monitor the served bundle" half of
  item 104).

Usage:
  python3 scripts/check_landing_integrity.py            # verify manifest
  python3 scripts/check_landing_integrity.py --write    # regenerate manifest
  python3 scripts/check_landing_integrity.py --self-test
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import sys

os.chdir(os.path.dirname(os.path.abspath(__file__)) + "/..")

LANDING_DIR = "design/landing"
MANIFEST = os.path.join(LANDING_DIR, "INTEGRITY.json")
SERVED_SUFFIXES = (".html", ".css", ".js")
HEADERS_FILE = os.path.join(LANDING_DIR, "_headers")

EXTERNAL_ASSET_RE = re.compile(
	r"""<(?:script|iframe|img|link|form|source|object)\b[^>]*?(?:src|href|action)\s*=\s*["'](https?:)?//""",
	re.IGNORECASE,
)
DANGEROUS_JS_RE = re.compile(r"\b(eval\s*\(|new\s+Function\s*\(|document\.write\s*\(|\.innerHTML\s*=)", re.IGNORECASE)
IFRAME_RE = re.compile(r"<iframe\b", re.IGNORECASE)

FAILURES: list[str] = []


def fail(message: str) -> None:
	FAILURES.append(message)


def sha256_text(text: str) -> str:
	return hashlib.sha256(text.encode("utf-8")).hexdigest()


def served_files() -> list[str]:
	files = []
	for name in sorted(os.listdir(LANDING_DIR)):
		path = os.path.join(LANDING_DIR, name)
		if os.path.isfile(path) and name.endswith(SERVED_SUFFIXES) and name != "INTEGRITY.json":
			files.append(name)
	return files


def read(path: str) -> str:
	with open(path, "r", encoding="utf-8") as handle:
		return handle.read()


def check_html(name: str, text: str) -> None:
	for match in EXTERNAL_ASSET_RE.finditer(text):
		line = text[:match.start()].count("\n") + 1
		fail(f"{LANDING_DIR}/{name}:{line}: external asset origin — landing pages must be fully same-origin (item 104)")
	if IFRAME_RE.search(text):
		fail(f"{LANDING_DIR}/{name}: iframe present — not allowed on a signing-adjacent origin (item 104)")
	match = DANGEROUS_JS_RE.search(text)
	if match:
		line = text[:match.start()].count("\n") + 1
		fail(f"{LANDING_DIR}/{name}:{line}: '{match.group(1).strip()}' is refused by CSP and hides code (item 104)")


def check_headers(text: str) -> None:
	required = {
		"content-security-policy": ["default-src 'self'", "connect-src 'none'", "frame-ancestors 'none'",
			"object-src 'none'", "base-uri"],
		"strict-transport-security": ["max-age="],
		"x-content-type-options": ["nosniff"],
	}
	lowered = text.lower()
	for header, needles in required.items():
		if header not in lowered:
			fail(f"{HEADERS_FILE}: missing header {header} (item 104)")
			continue
		line = next((l for l in text.splitlines() if l.strip().lower().startswith(header)), "")
		for needle in needles:
			if needle.lower() not in line.lower():
				fail(f"{HEADERS_FILE}: {header} is missing '{needle}' (item 104)")
	csp_line = next((l for l in text.splitlines() if l.strip().lower().startswith("content-security-policy")), "")
	script_src = re.search(r"script-src([^;]*)", csp_line, re.IGNORECASE)
	if script_src and re.search(r"https?://|\*", script_src.group(1)):
		fail(f"{HEADERS_FILE}: script-src allows an external origin (item 104)")
	if csp_line and "connect-src 'none'" not in csp_line.lower():
		fail(f"{HEADERS_FILE}: connect-src must stay 'none' on the static landing origin (item 104)")


def build_manifest() -> dict:
	entries = {}
	for name in served_files():
		entries[name] = sha256_text(read(os.path.join(LANDING_DIR, name)))
	return {
		"_comment": "Generated by scripts/check_landing_integrity.py --write. "
			"Any change here is a change to what players load: review it, then compare with the deployed bundle hash (catalog item 104).",
		"algorithm": "sha256",
		"files": entries,
	}


def check_manifest(manifest: dict) -> None:
	expected = manifest.get("files", {})
	actual = build_manifest()["files"]
	for name, digest in actual.items():
		if name not in expected:
			fail(f"{MANIFEST}: {name} is served but not hashed — run --write and review (item 104)")
		elif expected[name] != digest:
			fail(f"{MANIFEST}: {name} changed ({expected[name][:12]}… -> {digest[:12]}…) — "
				f"review the diff and regenerate (item 104)")
	for name in expected:
		if name not in actual:
			fail(f"{MANIFEST}: {name} is listed but no longer served (item 104)")


def self_test() -> None:
	import tempfile

	global FAILURES
	saved = FAILURES
	FAILURES = []
	try:
		check_html("fixture.html", '<script src="https://cdn.example/x.js"></script>')
		check_html("fixture.html", "<iframe src=\"//evil\"></iframe>")
		check_html("fixture.html", "<script>eval('x')</script>")
		messages = " | ".join(FAILURES)
		assert "external asset origin" in messages, FAILURES
		assert "iframe present" in messages, FAILURES
		assert "refused by CSP" in messages, FAILURES
		FAILURES = []
		check_html("fixture.html", '<script src="maps_data.js"></script><p>ok</p>')
		assert FAILURES == [], FAILURES

		good_headers = (
			"Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'; connect-src 'none'; "
			"frame-ancestors 'none'; object-src 'none'; base-uri 'self'\n"
			"Strict-Transport-Security: max-age=31536000; includeSubDomains\n"
			"X-Content-Type-Options: nosniff\n")
		check_headers(good_headers)
		assert FAILURES == [], FAILURES
		check_headers(good_headers.replace("script-src 'self'", "script-src https://cdn.example"))
		assert any("external origin" in message for message in FAILURES), FAILURES
		FAILURES = []
		check_headers(good_headers.replace("connect-src 'none'", "connect-src *"))
		assert FAILURES, "wildcard connect-src must fail"

		with tempfile.TemporaryDirectory() as tmp:
			assert sha256_text("a") == hashlib.sha256(b"a").hexdigest()
	finally:
		FAILURES = saved
	print("check_landing_integrity self-test: ok")


def main() -> int:
	if "--self-test" in sys.argv:
		self_test()
	if not os.path.isdir(LANDING_DIR):
		print(f"check_landing_integrity: {LANDING_DIR} absent — nothing to check")
		return 0
	for name in served_files():
		if name.endswith(".html"):
			check_html(name, read(os.path.join(LANDING_DIR, name)))
	if os.path.exists(HEADERS_FILE):
		check_headers(read(HEADERS_FILE))
	else:
		fail(f"{HEADERS_FILE}: missing — no CSP for the landing origin (item 104)")

	if "--write" in sys.argv:
		with open(MANIFEST, "w", encoding="utf-8") as handle:
			json.dump(build_manifest(), handle, indent=2, ensure_ascii=False)
			handle.write("\n")
		print(f"check_landing_integrity: wrote {MANIFEST}")
	else:
		if os.path.exists(MANIFEST):
			check_manifest(json.loads(read(MANIFEST)))
		else:
			fail(f"{MANIFEST}: missing — run --write and commit the result (item 104)")

	if FAILURES:
		for message in FAILURES:
			print(f"FAIL: {message}")
		print(f"check_landing_integrity: {len(FAILURES)} violation(s)")
		return 1
	print("check_landing_integrity: ok (same-origin assets, strict CSP, bundle hashes pinned)")
	return 0


if __name__ == "__main__":
	sys.exit(main())
