#!/usr/bin/env python3
"""Regenerate docs/ASSET_MANIFEST.csv.

Columns (required by the asset policy):

    path,sha256,type,author,copyright,license,source_url,attribution,action

Every file under the release asset roots (``data/``, ``other/icons/``,
``other/dmgbackground*.png``, ``other/emscripten/background.png``,
``assets-src/brand/``) gets exactly one row. ``action`` is one of:

* ``ship``           – may be redistributed in a commercial release today
                       (original artwork, or third-party work whose license and
                       attribution we can satisfy);
* ``block-release``  – vendored for development, but must not ship before the
                       rights review recorded in docs/THIRD_PARTY_NOTICES.md is
                       complete (``scripts/check_assets.sh --release`` fails).

Author/license facts are taken from the license files that ship with the assets
(``data/*/license.txt``) and from docs/UPSTREAM_AUDIT.md; where upstream names no
author the row says so explicitly instead of guessing.
"""

from __future__ import annotations

import csv
import hashlib
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
UPSTREAM_SHA = "a853d333ac9e61ebfa2899b4641f8b0658ba60d5"
UPSTREAM_URL = f"https://github.com/ddnet/ddnet/blob/{UPSTREAM_SHA}/"
OWN_URL = "https://github.com/Leo88q/neon-relay"

TYPES = {
    ".png": "image/png", ".ico": "image/x-icon", ".icns": "image/x-icns",
    ".map": "application/x-teeworlds-map", ".json": "application/json",
    ".txt": "text/plain", ".md": "text/markdown",
    ".ttf": "font/ttf", ".otf": "font/otf", ".ttc": "font/collection",
    ".wv": "audio/x-wavpack", ".rules": "text/plain",
    ".glsl": "text/x-glsl", ".vert": "text/x-glsl", ".frag": "text/x-glsl",
}

ORIGINAL_PREFIXES = (
    "data/gui_logo.png",
    "other/icons/NeonRelay",
    "other/dmgbackground",
    "other/emscripten/background.png",
    "data/menuimages/",
    "data/communityicons/none.png",
    "assets-src/brand/",
)

FONT_INFO = {
    "data/fonts/DejaVuSans.ttf": (
        "Bitstream, Inc. (Vera); Tavmjong Bah (Arev); DejaVu contributors",
        "Copyright (c) 2003 Bitstream, Inc.; Copyright (c) 2006 Tavmjong Bah",
        "Bitstream-Vera AND Arev AND public-domain",
        "https://dejavu-fonts.github.io/",
        "Bitstream Vera license + Arev license; DejaVu changes are public domain",
    ),
    "data/fonts/Font_Awesome_6_Free-Solid-900.otf": (
        "Fonticons, Inc.", "Copyright (c) 2023 Fonticons, Inc.", "OFL-1.1",
        "https://fontawesome.com/license/free",
        "SIL Open Font License 1.1; Reserved Font Name \"Font Awesome\"",
    ),
    "data/fonts/GlowSansJ-Compressed-Book.otf": (
        "Project Wêlai", "Copyright (c) 2020 Project Wêlai", "OFL-1.1",
        "https://github.com/welai/glow-sans",
        "SIL Open Font License 1.1",
    ),
    "data/fonts/SourceHanSans.ttc": (
        "Adobe", "Copyright (c) 2014-2021 Adobe", "OFL-1.1",
        "https://github.com/adobe-fonts/source-han-sans",
        "SIL Open Font License 1.1; Reserved Font Name \"Source\"",
    ),
}

MAP_INFO = {
    "Gold Mine.map": ("<BµmM>", "Copyright <BµmM>", "CC-BY-SA-3.0"),
    "LearnToPlay.map": ("Tridemy & Cøke", "Copyright Tridemy & Cøke", "CC-BY-SA-3.0"),
    "Sunny Side Up.map": (
        "Ravie", "Copyright Ravie", "CC-BY-SA-3.0",
        "grass_main is redrawn from the original Teeworlds grass_main mapres (Apache-2.0)",
    ),
    "Tsunami.map": ("louis", "Copyright louis", "CC-BY-SA-3.0"),
    "Tutorial.map": ("unique2 & Alisa", "Copyright unique2 & Alisa", "CC-BY-SA-3.0"),
}


def sha256(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


# Skins whose pixels are original Neon Relay work generated by
# scripts/build_neon_skins.py (stage 12). `default`, `x_ninja` and `x_spec`
# replace the upstream art in place because the game code references those
# names; the neon_* set are new additions.
GENERATED_SKINS = {
    "default", "x_ninja", "x_spec",
    "neon_cyan", "neon_magenta", "synthwave", "vaporgrid",
    "midnight", "circuit", "aurora", "glitch",
}


# UI art sheets whose pixels are original Neon Relay work generated by
# scripts/build_neon_ui_art.py (stage 16): same filenames and grids as the
# upstream sheets, drawn from scratch in the brand neon style.
GENERATED_UI_ART = {
    "data/emoticons.png", "data/particles.png", "data/gui_icons.png",
    "data/hud.png", "data/blob.png", "data/arrow.png", "data/race_flag.png",
    "data/strong_weak.png", "data/deadtee.png", "data/gui_cursor.png",
    "data/background_noise.png",
}


def parse_skin_licenses() -> dict[str, tuple[str, str, str]]:
    """Parse data/skins/license.txt into {skin stem: (author, copyright, license)}.

    The file is a sequence of blocks: a comma separated name list ending in ":",
    then a "Copyright <author>" line, then a "<license> license" line.
    """
    text = (ROOT / "data/skins/license.txt").read_text(encoding="utf-8")
    out: dict[str, tuple[str, str, str]] = {}
    names: list[str] = []
    buf = ""
    author: str | None = None
    copyright_: str | None = None
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("Copyright "):
            author = line[len("Copyright "):].strip()
            copyright_ = line
            continue
        m = re.match(r"^(CC-BY-SA|CC-BY|CC0|zlib) license", line)
        if m:
            lic = {"CC-BY-SA": "CC-BY-SA-3.0", "CC-BY": "CC-BY-4.0",
                   "CC0": "CC0-1.0", "zlib": "Zlib"}[m.group(1)]
            for name in names:
                out[name] = (author or "unknown", copyright_ or "unknown", lic)
            names, author, copyright_ = [], None, None
            continue
        if line.endswith(":"):
            buf += line[:-1] + " "
            names += [n.strip() for n in buf.split(",") if n.strip()]
            buf = ""
        else:
            buf += line + " "
    return out


def parse_language_attribution(path: pathlib.Path) -> str:
    try:
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            if line.startswith("== ") and " translation by " in line:
                return line[3:].strip()
    except OSError:
        pass
    return "authors listed inside the translation file"


def main() -> int:
    skins = parse_skin_licenses()
    rows: list[dict[str, str]] = []

    def add(rel: str, path: pathlib.Path, author: str, copyright_: str, license_: str,
            source: str, attribution: str, action: str) -> None:
        rows.append({
            "path": rel,
            "sha256": sha256(path),
            "type": TYPES.get(path.suffix.lower(), path.suffix or "file"),
            "author": author,
            "copyright": copyright_,
            "license": license_,
            "source_url": source,
            "attribution": attribution,
            "action": action,
        })

    watched: list[pathlib.Path] = []
    for base in ("data", "other/icons", "other/emscripten", "assets-src"):
        watched += sorted((ROOT / base).rglob("*"))
    watched += sorted(ROOT.glob("other/dmgbackground*.png"))
    watched = [p for p in watched if p.is_file()]

    unnamed = "DDNet contributors (no individual author named upstream)"
    unnamed_cc = "Copyright DDNet contributors (no individual author named upstream)"

    for path in watched:
        rel = path.relative_to(ROOT).as_posix()
        if rel.startswith("assets-src/maps/warm-workshops/"):
            add(rel, path, "Neon Relay project (AI-assisted generated artwork)",
                "AI-generated artwork; human copyright eligibility not assessed",
                "Zlib", OWN_URL,
                "Warm Workshops art-direction prototype; generated in Arena; not packaged as playable map assets; approval and integration pending",
                "block-release")
            continue
        if (rel.startswith("data/skins/potato_") and rel.endswith(".png")) or rel.startswith(("data/portraits/", "assets-src/potato/generated_bodies/")):
            add(rel, path, "Neon Relay project (AI-assisted generated artwork)",
                "AI-generated artwork; human copyright eligibility not assessed",
                "Zlib", OWN_URL,
                "Generated body illustrations; chroma/background removed to real RGBA; baked by scripts/build_potato_skins.py with separate animated limbs; fixed painted faces",
                "ship")
            continue
        if rel.startswith(("assets-src/potato/", "assets-src/weapons/", "data/skins/potato_")):
            add(rel, path, "Neon Relay project (AI-assisted artwork)",
                "AI-generated artwork; human copyright eligibility not assessed",
                "Zlib", OWN_URL,
                "Generated in Arena; processed by build_potato_skins.py / build_potato_weapon_sheet.py; not a pixel-identical import of user references",
                "ship")
            continue
        if rel.startswith(ORIGINAL_PREFIXES):
            add(rel, path, "The Neon Relay Authors", "(c) 2026 The Neon Relay Authors",
                "Zlib", f"{OWN_URL} (generated by scripts/build_brand_assets.py)",
                "original Neon Relay artwork, created for this project", "ship")
            continue
        if rel in ("data/extras.png", "data/strong_weak.png", "data/deadtee.png"):
            add(rel, path, "The Neon Relay Authors", "(c) 2026 The Neon Relay Authors",
                "Zlib", f"{OWN_URL} (generated by scripts/build_neon_misc_sheets.py)",
                "original Neon Relay misc sheet, created for this project (BL-15)", "ship")
            continue
        if (rel.startswith("data/skins/") and rel.endswith(".png")) or (
                rel.startswith("data/skins7/") and rel.endswith((".png", ".json"))):
            add(rel, path, "The Neon Relay Authors", "(c) 2026 The Neon Relay Authors",
                "Zlib", f"{OWN_URL} (generated by scripts/build_neon_skins.py / build_neon_skins_all.py)",
                "original Neon Relay skin artwork, created for this project (BL-15)", "ship")
            continue
        if rel.startswith("data/themes/nightdrive") or rel.startswith("data/game_entities/") or rel.startswith("data/countryflags/"):
            add(rel, path, "The Neon Relay Authors", "(c) 2026 The Neon Relay Authors",
                "Zlib", f"{OWN_URL} (generated by scripts/build_neon_editor_art.py / build_neon_background.py / build_neon_countryflags.py)",
                "original Neon Relay gameplay-overlay/theme/flag artwork, created for this project (BL-16)", "ship")
            continue
        if rel.startswith("data/audio/") and rel.endswith(".wav"):
            add(rel, path, "The Neon Relay Authors", "(c) 2026 The Neon Relay Authors",
                "Zlib", f"{OWN_URL} (generated by scripts/build_neon_sounds.py)",
                "original procedurally synthesised Neon Relay sound effect (BL-18)", "ship")
            continue
        if rel == "data/game.png":
            add(rel, path, "The Neon Relay Authors", "(c) 2026 The Neon Relay Authors",
                "Zlib", f"{OWN_URL} (generated by scripts/build_neon_game_sheet.py)",
                "original Neon Relay weapons/effects/flags sheet, created for this project (BL-15)", "ship")
            continue
        if rel.startswith("data/mapres/neonrelay_"):
            add(rel, path, "The Neon Relay Authors", "(c) 2026 The Neon Relay Authors",
                "Zlib", f"{OWN_URL} (generated by scripts/build_code_worlds.py (four code worlds) or legacy build_neon_tileset.py / build_neon_background.py)",
                "original Neon Relay map artwork, created for this project (BL-14)", "ship")
            continue
        if rel.startswith("data/maps/") and rel.endswith(".map"):
            add(rel, path, "The Neon Relay Authors", "(c) 2026 The Neon Relay Authors",
                "Zlib", f"{OWN_URL} (generated by scripts/build_neon_maps.py)",
                "original Neon Relay map, procedurally generated (BL-14)", "ship")
            continue
        if rel in FONT_INFO:
            a, c, l, s, note = FONT_INFO[rel]
            add(rel, path, a, c, l, s, note, "ship")
            continue
        if rel.startswith("data/languages/") and path.suffix == ".txt":
            if path.name in ("license.txt", "README.txt"):
                add(rel, path, "DDNet/Teeworlds translation contributors",
                    "see file", "CC-BY-SA-3.0", UPSTREAM_URL + rel,
                    "license/README notice for the translations", "ship")
            else:
                add(rel, path, "DDNet/Teeworlds translation contributors",
                    "see translation file header", "CC-BY-SA-3.0", UPSTREAM_URL + rel,
                    parse_language_attribution(path), "ship")
            continue
        if rel.startswith("data/maps/") and path.name in MAP_INFO:
            info = MAP_INFO[path.name]
            note = info[3] if len(info) > 3 else "named in data/maps/license.txt"
            add(rel, path, info[0], info[1], info[2], UPSTREAM_URL + rel, note, "ship")
            continue
        if rel.startswith("data/maps7/"):
            base = path.name
            if base in MAP_INFO:
                info = MAP_INFO[base]
                add(rel, path, info[0], info[1], info[2], UPSTREAM_URL + rel,
                    "0.7 conversion of the same map, made with src/tools/map_convert_07.cpp",
                    "ship")
            elif path.suffix == ".txt":
                add(rel, path, unnamed, unnamed_cc, "CC-BY-SA-3.0", UPSTREAM_URL + rel,
                    "readme notice for the converted maps", "block-release")
            else:
                add(rel, path, unnamed, unnamed_cc, "CC-BY-SA-3.0", UPSTREAM_URL + rel,
                    "0.7 conversion; upstream names no author", "block-release")
            continue
        if rel in GENERATED_UI_ART:
            add(rel, path, "The Neon Relay Authors", "(c) 2026 The Neon Relay Authors",
                "Zlib", f"{OWN_URL} (generated by scripts/build_neon_ui_art.py)",
                "original Neon Relay UI art, procedurally generated (stage 16); "
                "replaces upstream artwork in place over the same filename", "ship")
            continue
        if rel.startswith("data/skins/") and path.suffix == ".png":
            stem = path.stem
            if stem in GENERATED_SKINS:
                add(rel, path, "The Neon Relay Authors", "(c) 2026 The Neon Relay Authors",
                    "Zlib", f"{OWN_URL} (generated by scripts/build_neon_skins.py)",
                    "original Neon Relay skin, procedurally generated (stage 12); "
                    "replaces upstream artwork in place over the same filename", "ship")
            elif stem in skins:
                a, c, l = skins[stem]
                add(rel, path, a, c, l, UPSTREAM_URL + rel,
                    "named in data/skins/license.txt", "ship")
            else:
                add(rel, path, unnamed, unnamed_cc, "CC-BY-SA-3.0", UPSTREAM_URL + rel,
                    "falls under the unnamed 'all other skins' clause", "block-release")
            continue
        if rel.startswith("data/assets/entities/"):
            if path.name == "license.txt":
                add(rel, path, "louis", "Copyright louis", "CC-BY-SA-3.0",
                    UPSTREAM_URL + rel, "license notice for the comfort entity set", "ship")
            else:
                add(rel, path, "louis", "Copyright louis", "CC-BY-SA-3.0",
                    UPSTREAM_URL + rel, "named in data/assets/entities/license.txt", "ship")
            continue
        if rel.endswith(("license.txt", "readme.txt", "README.txt")):
            add(rel, path, "see file", "see file", "see file", UPSTREAM_URL + rel,
                "third-party license notice shipped with the assets", "ship")
            continue
        if rel.startswith("data/skins7/"):
            add(rel, path, "Teeworlds 0.7 contributors", "no per-file license upstream",
                "UNKNOWN", UPSTREAM_URL + rel,
                "Teeworlds 0.7 skin system; upstream names neither author nor license here",
                "block-release")
            continue
        add(rel, path, unnamed, unnamed_cc, "CC-BY-SA-3.0", UPSTREAM_URL + rel,
            "upstream ships no author list for this directory (see docs/UPSTREAM_AUDIT.md §3)",
            "block-release")

    out = ROOT / "docs/ASSET_MANIFEST.csv"
    with out.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=["path", "sha256", "type", "author", "copyright",
                                           "license", "source_url", "attribution", "action"])
        w.writeheader()
        for row in sorted(rows, key=lambda r: r["path"]):
            w.writerow(row)

    ship = sum(1 for r in rows if r["action"] == "ship")
    blocked = sum(1 for r in rows if r["action"] == "block-release")
    print(f"{out.relative_to(ROOT)}: {len(rows)} rows ({ship} ship, {blocked} block-release)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
