#!/usr/bin/env python3
"""Generate the classic skin selector allowlist from the catalog."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
rows = json.loads((ROOT / 'data/skins/potato_catalog.json').read_text())['skins']
assert len(rows) == 10 and len({row['id'] for row in rows}) == 10
header = '''// Generated by scripts/gen_potato_catalog.py. Do not edit.
#ifndef GAME_CLIENT_POTATO_CATALOG_H
#define GAME_CLIENT_POTATO_CATALOG_H
#include <base/str.h>
inline bool IsPotatoCatalogSkin(const char *pName)
{
\tstatic const char *const s_apNames[] = {
'''
for row in rows:
    assert row['id'].replace('_', '').isalnum()
    assert (ROOT / 'data/skins' / row['file']).is_file()
    header += '\t\t"' + row['id'] + '",\n'
header += '''\t};
\tfor(const char *pAllowed : s_apNames)
\t\tif(str_comp(pName, pAllowed) == 0)
\t\t\treturn true;
\treturn false;
}
#endif
'''
(ROOT / 'src/game/client/potato_catalog.h').write_text(header)
