#!/usr/bin/env python3
"""Generate the skin selector and character-page catalog from one manifest."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
rows = json.loads((ROOT / 'data/skins/potato_catalog.json').read_text())['skins']
assert len(rows) == 10 and len({row['id'] for row in rows}) == 10
header = '''// Generated by scripts/gen_potato_catalog.py. Do not edit.
#ifndef GAME_CLIENT_POTATO_CATALOG_H
#define GAME_CLIENT_POTATO_CATALOG_H
#include <base/str.h>
struct CPotatoCatalogEntry
{
	const char *m_pSkin;
	const char *m_pName;
	const char *m_pRarity;
	int m_PriceSkr;
	const char *m_pNameRu;
	const char *m_pTitle;
	const char *m_pTitleRu;
	const char *m_pSkill;
	const char *m_pSkillRu;
	const char *m_pLegend;
	const char *m_pLegendRu;
};
inline constexpr CPotatoCatalogEntry POTATO_CATALOG[] = {
'''
for row in rows:
    assert row['id'].replace('_', '').isalnum()
    assert (ROOT / 'data/skins' / row['file']).is_file()
    assert row['gameplay_bonuses'] is False
    values = [row['id'], row['name']['en'], row['rarity'], row['price_skr'], row['name']['ru'],
              row['title']['en'], row['title']['ru'], row['skill_lore']['en'], row['skill_lore']['ru'],
              row['legend']['en'], row['legend']['ru']]
    header += '\t{' + ', '.join(json.dumps(value, ensure_ascii=False) for value in values) + '},\n'
header += '''};
inline bool IsPotatoCatalogSkin(const char *pName)
{
	for(const auto &Entry : POTATO_CATALOG)
		if(str_comp(pName, Entry.m_pSkin) == 0)
			return true;
	return false;
}
#endif
'''
(ROOT / 'src/game/client/potato_catalog.h').write_text(header)
