/** Generate the offline client preview from the backend policy; not live data. */
import { writeFileSync } from "node:fs";
import { RACE_TIERS } from "../backend/src/race_catalog.ts";
let header = `// Generated by scripts/gen_race_catalog.ts. Do not edit.
#ifndef GAME_CLIENT_RACE_CATALOG_H
#define GAME_CLIENT_RACE_CATALOG_H
struct CRaceCatalogEntry
{
\tconst char *m_pName;
\tconst char *m_pPlayers;
\tconst char *m_pEntry;
\tbool m_LegendaryOnly;
};
inline constexpr CRaceCatalogEntry RACE_CATALOG[] = {
`;
for (const tier of RACE_TIERS) {
  const players = tier.minPlayers === null ? "—" : String(tier.minPlayers) + (tier.maxPlayers === null ? "+" : "");
  header += `\t{${JSON.stringify(tier.name)}, ${JSON.stringify(players)}, ${JSON.stringify(tier.entryTokens)}, ${tier.legendaryOnly}},\n`;
}
header += "};\n#endif\n";
writeFileSync(new URL("../src/game/client/race_catalog.h", import.meta.url), header);
